### ISSUE TITLE
VS2013 error compiling master on Windows

### ISSUE THREAD

**Issue by opticode** [viennacl/pyviennacl-dev#33]
Does anyone have build experience on Windows using Visual Studio?
I get the following compiler error on Windows, compiling latest master with VS2013, and for Python 2.7:

    src\_viennacl\platform_support.cpp(12) : error C2899:
      typename cannot be used outside a template declaration

And here is my batch file:

    call "\Apps\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"
    set MSSdk=1
    set DISTUTILS_USE_SDK=1 
    \python27\python.exe setup.py build

**Comment by karlrupp** [comment]
Ah, there are spurious extra 'typename' keywords in the code, which other compilers silently accept.
Please remove 'typename' in line 12 auf src/_viennacl/platform_support.cpp as well as in line 57. If you get the same error for other source code lines, repeat the procedure there.
(Once you have a working build it would be great if you could send us a pull request!)

**Comment by opticode** [comment]
Thanks Karl - that did the trick! I will fork, fix, and submit a pull request.

**Comment by opticode** [comment]
Fixed via #34.
