### ISSUE TITLE
anaconda

### ISSUE THREAD

**Issue by AJJLagerweij** [viennacl/pyviennacl-dev#43]
Dear developers,
I'm fairly new to python and was advised to use anaconda.
Now I have two main questions:
 1. How to install pyviennacl with anaconda (preferable through GUI)
 2. Does someone have experience with a MultiGrid solver implementation used for FEM

regargds

**Comment by geoeo** [comment]
I had the same question. I think the way to do it is to:

    $source activate <your environment>
    $pip install pyviennacl
